using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class newInput : MonoBehaviour {
	public string inputCombo;

	public GameObject happyFace, sadFace, loveFace;
	public GameObject flatter, joke, wink, chat, neutral;
	public Text meterText;
	public Text timeText;

	public bool comboOver;
	public bool StopButtons;
	public int preferedLength;
	public string[] combos;
	// Use this for initialization
	void Start () {

	}
	
	// Update is called once per frame
	void Update () {
		//Get player input. 
		if (inputCombo.Length < 5 && comboOver == false) {
			if (Input.GetKeyDown (KeyCode.A)) {
				inputCombo += "A";
				Debug.Log ("Your combo so far: " + inputCombo);

			} else if (Input.GetKeyDown (KeyCode.W)) {
				inputCombo += "W";
				Debug.Log ("Your combo so far: " + inputCombo);
			} else if (Input.GetKeyDown (KeyCode.S)) {
				inputCombo += "S";
				Debug.Log ("Your combo so far: " + inputCombo);
			} else if (Input.GetKeyDown (KeyCode.D)) {
				inputCombo += "D";
				Debug.Log ("Your combo so far: " + inputCombo);
			}
			else if(Input.GetKeyDown(KeyCode.Space)){
				comboOver = true;
				Debug.Log ("Press [R] to reset" + CompareCombo (preferedLength, inputCombo, combos));

			}

		}
		else { 
			if(Input.GetKeyDown(KeyCode.R)){ 
				comboOver = false;
				inputCombo = "";
				Debug.Log ("REset the combo, see :" + inputCombo);
			}
		}
	}

	//<-------------------------------Functions----------------------->
	string CompareCombo(int preferedComboLength, string playerCombo, string[] comboList){ 
		/*the length that we want the combo to be (3-5), 
		 *the combo generated by the player, 
		 *the list of combo we've given meaning to.
		*/

		string isIt = "";//the final string of info
		bool premade = false;

		//testing length
		if(playerCombo.Length>preferedLength){ isIt += "long";}
		else{ isIt += "fit";}//langauge reflects length in attempts for improved readability

		for(int i = 0; i<comboList.Length; i++)//Checks if the inputCOmbo exist in the combo list
		{
			if(comboList[i].Equals( playerCombo)){
				isIt += " " + i;
				premade = true;
				Debug.Log ("We checked "+i+" and that was one.  >" + playerCombo);
				break;
			} 


		}
		if(premade==false){isIt+=" -1";}//combos not on the list are denoted by -1.

		return isIt;
	}

}






